export const API_REQUEST = "API_REQUEST";

export const API_SUCCESS = "API_SUCCESS";

export const API_ERROR = "API_ERROR";

export const SET_DEPARTMENT_DATA = "SET_DEPARTMENT_DATA";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const DATE_RANGE_FLAG = "DATE_RANGE_FLAG";
export const SET_USER_PREFRENCE = "SET_USER_PREFRENCE";
export const USER_LOGIN = "USER_LOGIN";
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const SET_DB_PREFRENCE = "SET_DB_PREFRENCE";
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";